### ISSUE TITLE
Problem: needs explanation of contractAddress in config.json 

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-initial-keys#2]
How and where do you get those addresses from? 
https://github.com/oraclesorg/oracles-initial-keys/blob/master/config.json#L12

Also is there source code for those contracts?

**Comment by phahulin** [comment]
This is the same address as used in spec.json for governance contract
https://github.com/oraclesorg/oracles-scripts/blob/master/spec.json#L82
